name: ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
    - run: echo "DATE=$(date -u +"%Y-%m-%d")" >> $GITHUB_ENV
    - run: echo "IMAGE_TAG=$DATE-$SHORT_SHA" >> $GITHUB_ENV
    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $IMAGE_TAG .
